services:
  verusd_varrr:
    hostname: ${VERUSD_HOSTNAME}
    image: verustrading/verusd:0.1
    command: verusd -chain=${CHAIN_NAME} ${VERUSD_BOOTSTRAP_FLAG}
    volumes:
      - ./data_dir:/root/.verus/pbaas/${CURRENCYID_HEX}
      #- ./VRSC.conf:/root/.komodo/VRSC/VRSC.conf
      - /home/${USER}/.zcash-params:/root/.zcash-params:ro
    networks:
      pbaas_network:
        ipv4_address: ${VERUSD_IPV4}
    logging:
      driver: "json-file"
    stop_grace_period: 2m

networks:
  pbaas_network:
    name: ${DOCKER_NETWORK_NAME}
    external: true
